<a href="https://colab.research.google.com/github/QVIVEK/Abstract-classification-ML/blob/master/Abstract-classification-ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

In [ ]:
print("Test local")

Test local

In [13]:
import pandas as pd

# Corrected URL path and spelling ('bussiness' with double 's' and branch 'main')
csv_url = '/business_raw_20000.csv'
df = pd.read_csv(csv_url)
display(df.head())

,Link,Abstract,Author Keywords,Index Keywords
0,https://www.scopus.com/pages/publications/1050...,Age discrimination against younger employees h...,Age discrimination against younger employees; ...,NaN
1,https://www.scopus.com/pages/publications/1050...,One of the key challenges in the hospitality i...,Flexible work hours system; Human resources; O...,NaN
2,https://www.scopus.com/pages/publications/1050...,"Under scarce viewer attention, video covers se...",Digital marketing; Generative AI; Machine lear...,NaN
3,https://www.scopus.com/pages/publications/1050...,This study analyzes how the dispersion of prio...,Online reviews; Prospect theory; Rating varian...,NaN
4,https://www.scopus.com/pages/publications/1050...,Sustainable Aviation Fuel (SAF) is a key near-...,Aviation; Financing framework; Scope 3 emissio...,NaN

Data Sourcing
Through Scopus advance Search  
for business : SUBJAREA ( BUSI ) AND ( LIMIT-TO ( DOCTYPE , "cp" ) OR LIMIT-TO ( DOCTYPE , "ar" ) ) AND ( LIMIT-TO ( SRCTYPE , "j" ) OR LIMIT-TO ( SRCTYPE , "p" ) OR LIMIT-TO ( SRCTYPE , "d" ) ) truncated to 20000 latest results (limit of scopus export)

In [15]:
# Removing link and adding serial number, also deleting entries with no abstract, also adding one column with attribute business
import pandas as pd
import numpy as np

# Explicitly drop the 'Link' column and ignore errors if already dropped
df = df.drop(columns=['Link'], errors='ignore')

#Delete entries with no abstract
col_name = "Abstract"
df = df.dropna(subset=[col_name])
df = df[df[col_name].astype(str).str.strip() != '']

#Add a sequential Serial Number column at the beginning
if 'Serial Number' not in df.columns:
    df.insert(0, 'Serial Number', range(1, len(df) + 1))

#Add a column with the attribute 'business'
df['attribute'] = 'business'
print(df.count())

# Display the cleaned DataFrame
display(df.head())

# Export the cleaned DataFrame to a CSV file
df.to_csv('business_cleaned.csv', index=False)

Serial Number      20000
Abstract           20000
Author Keywords    17890
Index Keywords      7230
attribute          20000
dtype: int64

,Serial Number,Abstract,Author Keywords,Index Keywords,attribute
0,1,Age discrimination against younger employees h...,Age discrimination against younger employees; ...,NaN,business
1,2,One of the key challenges in the hospitality i...,Flexible work hours system; Human resources; O...,NaN,business
2,3,"Under scarce viewer attention, video covers se...",Digital marketing; Generative AI; Machine lear...,NaN,business
3,4,This study analyzes how the dispersion of prio...,Online reviews; Prospect theory; Rating varian...,NaN,business
4,5,Sustainable Aviation Fuel (SAF) is a key near-...,Aviation; Financing framework; Scope 3 emissio...,NaN,business

In [16]:
from google.colab import files

# Download the exported cleaned CSV file to your local computer
files.download('business_cleaned.csv')

In [18]:
csv_url = '/soci_raw_20000.csv'
df = pd.read_csv(csv_url)
display(df.head())
# Explicitly drop the 'Link' column and ignore errors if already dropped
df = df.drop(columns=['Link'], errors='ignore')

#Delete entries with no abstract
col_name = "Abstract"
df = df.dropna(subset=[col_name])
df = df[df[col_name].astype(str).str.strip() != '']

#Add a sequential Serial Number column at the beginning
if 'Serial Number' not in df.columns:
    df.insert(0, 'Serial Number', range(1, len(df) + 1))

#Add a column with the attribute 'business'
df['attribute'] = 'Soci'
print(df.count())

# Display the cleaned DataFrame
display(df.head())

# Export the cleaned DataFrame to a CSV file
df.to_csv('soci_cleaned.csv', index=False)
files.download('soci_cleaned.csv')

,Link,Abstract,Author Keywords,Index Keywords
0,https://www.scopus.com/pages/publications/1050...,Aemilia Lanyer-s relationship to the prospecti...,Aemilia Lanyer; blood piety; female community;...,NaN
1,https://www.scopus.com/pages/publications/1050...,Sector-level environmental assessment of minin...,Environmental footprint; Environmental impact ...,Croatia; Environmental impact assessments; Env...
2,https://www.scopus.com/pages/publications/1050...,The transportation sector contributes over a q...,Environmental break-even analysis; Hydrogen fu...,Canada; Quebec [Canada]; Automobiles; Carbon c...
3,https://www.scopus.com/pages/publications/1050...,This study examines the economic resilience of...,COVID-19 pandemic; Neighborhood commercial dis...,NaN
4,https://www.scopus.com/pages/publications/1050...,"In modern society, an increasing number of peo...",Data narratives; Data-enabled reflection; Mult...,Behavioral research; Data mining; Information ...

Serial Number      19999
Abstract           19999
Author Keywords    16380
Index Keywords      7742
attribute          19999
dtype: int64

,Serial Number,Abstract,Author Keywords,Index Keywords,attribute
0,1,Aemilia Lanyer-s relationship to the prospecti...,Aemilia Lanyer; blood piety; female community;...,NaN,Soci
1,2,Sector-level environmental assessment of minin...,Environmental footprint; Environmental impact ...,Croatia; Environmental impact assessments; Env...,Soci
2,3,The transportation sector contributes over a q...,Environmental break-even analysis; Hydrogen fu...,Canada; Quebec [Canada]; Automobiles; Carbon c...,Soci
3,4,This study examines the economic resilience of...,COVID-19 pandemic; Neighborhood commercial dis...,NaN,Soci
4,5,"In modern society, an increasing number of peo...",Data narratives; Data-enabled reflection; Mult...,Behavioral research; Data mining; Information ...,Soci

In [20]:
import pandas as pd
from google.colab import files

csv_url = '/sci_raw_20000.csv'
# Fixed by using the 'python' engine and on_bad_lines to handle formatting issues / unclosed quotes
try:
    df = pd.read_csv(csv_url, engine='python', on_bad_lines='skip')
except Exception as e:
    # Fallback option if there are still issues
    df = pd.read_csv(csv_url, error_bad_lines=False, warn_bad_lines=True)

display(df.head())
# Explicitly drop the 'Link' column and ignore errors if already dropped
df = df.drop(columns=['Link'], errors='ignore')

#Delete entries with no abstract
col_name = "Abstract"
df = df.dropna(subset=[col_name])
df = df[df[col_name].astype(str).str.strip() != '']

#Add a sequential Serial Number column at the beginning
if 'Serial Number' not in df.columns:
    df.insert(0, 'Serial Number', range(1, len(df) + 1))

#Add a column with the attribute 'business'
df['attribute'] = 'Science'
print(df.count())

# Display the cleaned DataFrame
display(df.head())

# Export the cleaned DataFrame to a CSV file
df.to_csv('sci_cleaned.csv', index=False)
files.download('sci_cleaned.csv')

,Link,Abstract,Author Keywords,Index Keywords
0,https://www.scopus.com/pages/publications/1050...,Ants (Hymenoptera: Formicidae) are integral co...,abundance; diversity indices; Edough Massif; e...,NaN
1,https://www.scopus.com/pages/publications/1050...,A pot culture experiment evaluated the dissipa...,Anthranilic diamide; Eisenia fetida; environme...,NaN
2,https://www.scopus.com/pages/publications/1050...,"In this scientific article, the material compo...",fluorescent spectrometer; granulometric compos...,NaN
3,https://www.scopus.com/pages/publications/1050...,We introduce and analyze a static piezoelectri...,Clarke generalized derivative; Double hemivari...,Contacts (fluid mechanics); Electric contacts;...
4,https://www.scopus.com/pages/publications/1050...,Self-assembled monolayers (SAMs) are widely us...,Interface engineering; Organic solar cells; Sc...,Blending; Conversion efficiency; Defects; Indi...

Serial Number      19998
Abstract           19998
Author Keywords    19713
Index Keywords     17799
attribute          19998
dtype: int64

,Serial Number,Abstract,Author Keywords,Index Keywords,attribute
0,1,Ants (Hymenoptera: Formicidae) are integral co...,abundance; diversity indices; Edough Massif; e...,NaN,Science
1,2,A pot culture experiment evaluated the dissipa...,Anthranilic diamide; Eisenia fetida; environme...,NaN,Science
2,3,"In this scientific article, the material compo...",fluorescent spectrometer; granulometric compos...,NaN,Science
3,4,We introduce and analyze a static piezoelectri...,Clarke generalized derivative; Double hemivari...,Contacts (fluid mechanics); Electric contacts;...,Science
4,5,Self-assembled monolayers (SAMs) are widely us...,Interface engineering; Organic solar cells; Sc...,Blending; Conversion efficiency; Defects; Indi...,Science

In [22]:
%pip install  arxiv

Collecting arxiv
  Downloading arxiv-4.0.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: lxml<7.0,>=6.1.0 in /usr/local/lib/python3.13/dist-packages (from arxiv) (6.1.3)
Requirement already satisfied: requests<2.35,>=2.32 in /usr/local/lib/python3.13/dist-packages (from arxiv) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<2.35,>=2.32->arxiv) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<2.35,>=2.32->arxiv) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<2.35,>=2.32->arxiv) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<2.35,>=2.32->arxiv) (2026.7.22)
Downloading arxiv-4.0.1-py3-none-any.whl (13 kB)
Installing collected packages: arxiv
Successfully installed arxiv-4.0.1